# Generated by Django 4.2.4 on 2023-11-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_converted_date_client_firm_client_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='team',
        ),
    ]
