# Generated by Django 4.2.4 on 2023-11-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_team_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='plan',
        ),
    ]
