# Generated by Django 4.2.4 on 2023-11-19 12:28

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_active_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='active_team',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_function',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=userprofile.models.get_default_profile_image, max_length=255, null=True, upload_to=userprofile.models.get_profile_image_filepath),
        ),
    ]
