# Generated by Django 4.2.1 on 2023-08-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_leadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date_conversion_en_client'),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(default=1, max_length=20, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Téléphone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
