# Generated by Django 4.2.4 on 2023-11-19 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_alter_lead_firm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='team',
        ),
    ]
