# Generated by Django 4.2.4 on 2023-11-20 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_remove_team_plan'),
        ('lead', '0011_remove_lead_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_comments', to='team.team', verbose_name='Equipe'),
        ),
    ]
