# Generated by Django 4.2.4 on 2023-11-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_alter_comment_team'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('first_name', 'name')},
        ),
    ]
